export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "E_AUTH_INVALID_CREDENTIALS",
  AUTH_INVALID_REFRESH_TOKEN: "E_AUTH_INVALID_REFRESH_TOKEN",
  AUTH_NO_REFRESH_TOKEN: "E_AUTH_NO_REFRESH_TOKEN",
  AUTH_REQUIRED: "E_AUTH_REQUIRED",
  AUTH_ADMIN_REQUIRED: "E_AUTH_ADMIN_REQUIRED",
  AUTH_DUPLICATE_NICKNAME: "E_AUTH_DUPLICATE_NICKNAME",
  AUTH_DUPLICATE_EMAIL: "E_AUTH_DUPLICATE_EMAIL",

  POST_NOT_FOUND: "E_POST_NOT_FOUND",
  POST_NOT_OWNER: "E_POST_NOT_OWNER",
  POST_PLAN_LIMIT: "E_POST_PLAN_LIMIT",
  POST_PET_DETAIL_REQUIRED: "E_POST_PET_DETAIL_REQUIRED",
  POST_LOCATION_REQUIRED: "E_POST_LOCATION_REQUIRED",
  POST_IMAGE_LIMIT: "E_POST_IMAGE_LIMIT",
  POST_LOST_DATE_REQUIRED: "E_POST_LOST_DATE_REQUIRED",
  POST_SELF_FAVORITE: "E_POST_SELF_FAVORITE",
  POST_FAVORITE_LIMIT: "E_POST_FAVORITE_LIMIT",
  POST_IMAGE_NOT_FOUND: "E_POST_IMAGE_NOT_FOUND",

  USER_NOT_FOUND: "E_USER_NOT_FOUND",
  USER_NICKNAME_REQUIRED: "E_USER_NICKNAME_REQUIRED",

  CONV_NOT_FOUND: "E_CONV_NOT_FOUND",
  CONV_NOT_PARTICIPANT: "E_CONV_NOT_PARTICIPANT",
  CONV_CREATE_FORBIDDEN: "E_CONV_CREATE_FORBIDDEN",
  CONV_MESSAGE_FORBIDDEN: "E_CONV_MESSAGE_FORBIDDEN",
  CONV_CONTENT_REQUIRED: "E_CONV_CONTENT_REQUIRED",
  CONV_CONTENT_TOO_LONG: "E_CONV_CONTENT_TOO_LONG",
  CONV_SIGHTING_NOT_LINKED: "E_CONV_SIGHTING_NOT_LINKED",

  SIGHTING_NOT_FOUND: "E_SIGHTING_NOT_FOUND",
  SIGHTING_SELF_CREATE: "E_SIGHTING_SELF_CREATE",
  SIGHTING_NOT_OWNER: "E_SIGHTING_NOT_OWNER",
  SIGHTING_SELF_FAVORITE: "E_SIGHTING_SELF_FAVORITE",
  SIGHTING_FAVORITE_LIMIT: "E_SIGHTING_FAVORITE_LIMIT",
  SIGHTING_POST_ID_REQUIRED: "E_SIGHTING_POST_ID_REQUIRED",

  RESOURCE_NOT_FOUND: "E_RESOURCE_NOT_FOUND",
  RESOURCE_DUPLICATE: "E_RESOURCE_DUPLICATE",

  FILE_INVALID_ID: "E_FILE_INVALID_ID",
  FILE_INVALID_PATH: "E_FILE_INVALID_PATH",
  FILE_SIZE_EXCEEDED: "E_FILE_SIZE_EXCEEDED",
  FILE_UNSUPPORTED_TYPE: "E_FILE_UNSUPPORTED_TYPE",

  IMAGE_PROCESSING_ERROR: "E_IMAGE_PROCESSING_ERROR",

  RATE_LIMIT: "E_RATE_LIMIT",

  VALIDATION: "E_VALIDATION",

  INTERNAL: "E_INTERNAL",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
