/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API description
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export interface LoginDto {
  email: string;
  password: string;
}

export interface UpdatePostDto {
  content?: string;
  title?: string;
}

export interface CreatePostDto {
  content: string;
  title: string;
}

export interface RegisterDto {
  email: string;
  name?: string;
  password: string;
}





  export const usersControllerRegister = <TData = AxiosResponse<void>>(
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/users/register`,
      registerDto,options
    );
  }

export const postsControllerCreate = <TData = AxiosResponse<void>>(
    createPostDto: CreatePostDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/posts`,
      createPostDto,options
    );
  }

export const postsControllerList = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/posts`,options
    );
  }

export const postsControllerGet = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/posts/${id}`,options
    );
  }

export const postsControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updatePostDto: UpdatePostDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/posts/${id}`,
      updatePostDto,options
    );
  }

export const postsControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/posts/${id}`,options
    );
  }

export const authControllerLogin = <TData = AxiosResponse<void>>(
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/login`,
      loginDto,options
    );
  }

export const authControllerRefresh = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/refresh`,undefined,options
    );
  }

export const authControllerLogout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/logout`,undefined,options
    );
  }

export type UsersControllerRegisterResult = AxiosResponse<void>
export type PostsControllerCreateResult = AxiosResponse<void>
export type PostsControllerListResult = AxiosResponse<void>
export type PostsControllerGetResult = AxiosResponse<void>
export type PostsControllerUpdateResult = AxiosResponse<void>
export type PostsControllerRemoveResult = AxiosResponse<void>
export type AuthControllerLoginResult = AxiosResponse<void>
export type AuthControllerRefreshResult = AxiosResponse<void>
export type AuthControllerLogoutResult = AxiosResponse<void>
