/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API description
 * OpenAPI spec version: 1.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
export type PostsControllerUpdateBody = {
  description?: string;
  title?: string;
};

export type PostsControllerCreateBody = {
  description?: string;
  lostDate?: string;
  title?: string;
};

export interface LogoutResponseDto {
  ok: boolean;
}

export interface AccessTokenResponseDto {
  accessToken: string;
}

export interface LoginDto {
  email: string;
  /** @minLength 8 */
  password: string;
}

export interface PostResponseDto {
  createdAt: string;
  description: string;
  id: string;
  lostDate: string;
  /** @nullable */
  title?: string | null;
  userId: string;
}

export interface PostListResponseDto {
  items: PostResponseDto[];
  total: number;
}

export interface UserResponseDto {
  createdAt: string;
  email: string;
  id: string;
  /** @nullable */
  name?: string | null;
}

export interface RegisterDto {
  email: string;
  name?: string;
  /** @minLength 8 */
  password: string;
}

export const usersControllerRegister = <TData = AxiosResponse<UserResponseDto>>(
  registerDto: RegisterDto,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/users/register`, registerDto, options);
};

export const postsControllerCreate = <TData = AxiosResponse<PostResponseDto>>(
  postsControllerCreateBody: PostsControllerCreateBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  const formData = new FormData();
  if (postsControllerCreateBody.title !== undefined) {
    formData.append("title", postsControllerCreateBody.title);
  }
  if (postsControllerCreateBody.description !== undefined) {
    formData.append("description", postsControllerCreateBody.description);
  }
  if (postsControllerCreateBody.lostDate !== undefined) {
    formData.append("lostDate", postsControllerCreateBody.lostDate);
  }

  return axios.post(`/api/posts`, formData, options);
};

export const postsControllerList = <TData = AxiosResponse<PostListResponseDto>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/posts`, options);
};

export const postsControllerGet = <TData = AxiosResponse<PostResponseDto>>(
  id: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/posts/${id}`, options);
};

export const postsControllerUpdate = <TData = AxiosResponse<PostResponseDto>>(
  id: string,
  postsControllerUpdateBody: PostsControllerUpdateBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  const formData = new FormData();
  if (postsControllerUpdateBody.title !== undefined) {
    formData.append("title", postsControllerUpdateBody.title);
  }
  if (postsControllerUpdateBody.description !== undefined) {
    formData.append("description", postsControllerUpdateBody.description);
  }

  return axios.put(`/api/posts/${id}`, formData, options);
};

export const postsControllerRemove = <TData = AxiosResponse<PostResponseDto>>(
  id: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/posts/${id}`, options);
};

export const authControllerLogin = <
  TData = AxiosResponse<AccessTokenResponseDto>,
>(
  loginDto: LoginDto,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/auth/login`, loginDto, options);
};

export const authControllerRefresh = <
  TData = AxiosResponse<AccessTokenResponseDto>,
>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/auth/refresh`, undefined, options);
};

export const authControllerLogout = <TData = AxiosResponse<LogoutResponseDto>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/auth/logout`, undefined, options);
};

export type UsersControllerRegisterResult = AxiosResponse<UserResponseDto>;
export type PostsControllerCreateResult = AxiosResponse<PostResponseDto>;
export type PostsControllerListResult = AxiosResponse<PostListResponseDto>;
export type PostsControllerGetResult = AxiosResponse<PostResponseDto>;
export type PostsControllerUpdateResult = AxiosResponse<PostResponseDto>;
export type PostsControllerRemoveResult = AxiosResponse<PostResponseDto>;
export type AuthControllerLoginResult = AxiosResponse<AccessTokenResponseDto>;
export type AuthControllerRefreshResult = AxiosResponse<AccessTokenResponseDto>;

export interface MarkerDto {
  lat: number;
  lng: number;
  title: string;
  description: string;
  imageUrl?: string;
}

export const mapControllerGetMarkers = <TData = AxiosResponse<MarkerDto[]>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/map/markers`, options);
};

export type MapControllerGetMarkersResult = AxiosResponse<MarkerDto[]>;
export type AuthControllerLogoutResult = AxiosResponse<LogoutResponseDto>;
